def show_help():
    print()
    print("╔══════════════════════════════════════════════════════╗")
    print("║                  RUDRA COMMANDS                      ║")
    print("╠══════════════════════════════════════════════════════╣")
    print("║                                                      ║")
    print("║  SYSTEM                                               ║")
    print("║  • current time                                      ║")
    print("║  • current date                                      ║")
    print("║  • system info                                       ║")
    print("║  • list files                                        ║")
    print("║                                                      ║")
    print("║  FILES                                                ║")
    print("║  • create folder <name>                              ║")
    print("║  • create file <name> <text>                         ║")
    print("║  • read file <name>                                  ║")
    print("║  • check file <name>                                 ║")
    print("║                                                      ║")
    print("║  MEMORY                                               ║")
    print("║  • show memory                                       ║")
    print("║  • clear memory                                      ║")
    print("║                                                      ║")
    print("║  SECURITY                                             ║")
    print("║  • control center                                    ║")
    print("║                                                      ║")
    print("║  SESSION                                              ║")
    print("║  • exit                                               ║")
    print("║                                                      ║")
    print("╚══════════════════════════════════════════════════════╝")
    print()